### ISSUE TITLE
Day 59: Milestone Project 13-15

### ISSUE THREAD

**Issue by leonardsangoroh** [twostraws/HackingWithSwift#102]
Hey everyone, I am having a challenge with loading the names of the country (from my created [JSON file](https://github.com/leonardsangoroh/AfricanCountriesInfo/blob/main/AfricanCountriesInfo/Countries%20JSON%20File/countries.json)) to the table view. If you can kindly assist, here is the link to the GitHub repository where the project resides: https://github.com/leonardsangoroh/AfricanCountriesInfo Any help will be much appreciated.

Thank you in advance :)

**Comment by twostraws** [comment]
GitHub isn't a great place for seeking advice with your code. Can I suggest you join the Hacking with Swift Slack workspace? It's at hackingwithswift.com/slack.
