### ISSUE TITLE
No folder called content 

### ISSUE THREAD

**Issue by jknash101** [twostraws/HackingWithSwift#16]
"You'll see another folder in there called project1 and inside that folder called content." there is not folder called Content i will down load the image files individually but it does lead to confusion for novice users. Like myself 
Hope you don't mind the feedback

**Comment by bastilimbach** [comment]
@jknash101 The content folder is inside the [project1-files](https://github.com/twostraws/HackingWithSwift/tree/master/project1-files/Content) folder.
@twostraws I would change "[...] called project1 [...]" to "[...] called project1-files [...]" on page 100.

**Comment by jknash101** [comment]
ok i got you I now see there are 2 files thanks for the help... onto project 2 today... been

**Comment by johntamch** [comment]
@twostraws got the same problem while following the tutorial online.  Suggest to update the folder name in the free tutorial too.

**Comment by twostraws** [comment]
I'm on it!
