### ISSUE TITLE
Project 30 timer code not matching with book text

### ISSUE THREAD

**Issue by jakedgrant** [twostraws/HackingWithSwift#25]
Code in project file:
https://github.com/twostraws/HackingWithSwift/blob/db581a1aee7c08d387addc12564f717751550e29/project30-files/Project30/ImageViewController.swift#L38

Code in book text:
```
self.animTimer = Timer.scheduledTimerWithTimeInterval(5, target: self, selector: #selector(animateImage), userInfo: nil, repeats: true)
```

Looks like the book text needs updated since `scheduledTimer(withTimeInterval:repeats:block)` is the current syntax.

**Comment by twostraws** [comment]
Thanks! This will be fixed in the next update.
