### ISSUE TITLE
Project 13

### ISSUE THREAD

**Issue by PPacie** [twostraws/HackingWithSwift#4]
Calling the following line of code generates a memory warning and the application is terminated:

```swift 
let cgimg = context.createCGImage(currentFilter.outputImage!, fromRect: currentFilter.outputImage!.extent)
```

You can test it by moving the filter slider a couple of times. The memory of the App itself remains stable. I have not been able to detect any leak using Instruments.

As It doesn't happen in iOS8.4.1 with Swift 1.2, I do believe that the issue is in iOS9, but not 100% sure.

Just in case, I've opened a radar **`22844426`**.

Cheers,
Pablo.

**Comment by twostraws** [comment]
This is because we're allocating and freeing a lot of RAM, so iOS detects memory pressure and kills the app. If you want to use this sort of code in a real app, and want to continue operating on large pictures, you should set `continuous` to be false on the slider.

**Comment by PPacie** [comment]
Actually, there was an issue related to CIContext in iOS9.0 that was fixed in iOS9.1. The same code now works fine with no crashes as it did in iOS8.4.1.

Anyway, thanks for the tip about the  ```continuous``` on the slider, will keep an eye on that too =)
