### ISSUE TITLE
Instructions could be a bit clearer

### ISSUE THREAD

**Issue by gitonthescene** [twostraws/HackingWithSwift#44]
First of all, thank you so much for putting this together!

FWIW, I'm following along with the first project found here:  https://www.hackingwithswift.com/read/1/1/setting-up

I came here to clone the repository, but it wasn't clear that I needed to look under the Classic folder.  There's also a project1 folder in SwiftUI, but no project1-files folder.

I'm not complaining, I just thought you might find the feedback useful.

Thanks again,
-Doug

**Comment by mdeaconu** [comment]
hey @gitonthescene, if you do not mind the README.md file has that clarification you are looking for ... `There is **one folder** for the classic Hacking with Swift course, which teaches UIKit and SpriteKit, and **another folder** for the SwiftUI edition.` :)

**Comment by gitonthescene** [comment]
Fair enough.   I was thinking the website could be updated but I’ll leave that to your discretion.  Thanks again for putting together a great introduction to Swift.
