### ISSUE TITLE
Help wanted!! Project 7

### ISSUE THREAD

**Issue by zerotwoswift** [twostraws/HackingWithSwift#49]
I'm just having issues with my code that arent apparent, ie there arent any warnings or issue signs, the app wont display the content and I'm really not sure on how to fix it.
For further info and a short video, follow this link to my twitter post:
https://twitter.com/zerotwowaifu1/status/1288200584793907203

_ps: sorry I'm new to GitHub and I don't know how to label stuff before sending_

**Comment by twostraws** [comment]
You should ask questions on the forums, not here: https://www.hackingwithswift.com/forums
