### ISSUE TITLE
Project 1

### ISSUE THREAD

**Issue by ghreat** [twostraws/HackingWithSwift#5]
Might be the wrong place to report this, but there's a spelling error on https://www.hackingwithswift.com/read/1/4/introducing-interface-builder

It's an adaptive segue (part of the "adaptive user interfaces" way of working) and it means "on iPhone, animate in from the right, but on iPad just change the detail view ***conntroller***."

**Comment by ghreat** [comment]
On https://www.hackingwithswift.com/read/1/5/loading-images-with-uiimage:

This means "I know you think that the destination view controller is a regular UIViewController, but trust me: it's actually a ***UIViewController***."

The ***UIViewController*** should read UINavigationController if I'm not mistaken.

**Comment by twostraws** [comment]
Would it be possible to use email rather than GitHub for reporting these? I'm paul@hackingwithswift.com. If email isn't possible, then perhaps Twitter? I'm @twostraws there.
