### ISSUE TITLE
URL to download all project files 404s

### ISSUE THREAD

**Issue by JimMargolis** [twostraws/HackingWithSwift#52]
The link in the [Day 16 instructions](https://www.hackingwithswift.com/read/1/1/setting-up) gives a 404 error:

<img width="884" alt="Screen Shot 2020-10-14 at 8 52 09 AM" src="https://user-images.githubusercontent.com/57914060/96006300-9227d080-0dfa-11eb-8273-4a68ca6808cb.png">

https://github.com/twostraws/HackingWithSwift/archive/master.zip

**Comment by hozra** [comment]
On the main page, there's the "Code" button, where You can clone the whole repository or download all projects as a zip file, a 165 MB download. I suppose that it is the one You want to download

**Comment by twostraws** [comment]
This is resolved now – thank you!
