### ISSUE TITLE
Project 1 files 

### ISSUE THREAD

**Issue by JohnDavidGit** [twostraws/HackingWithSwift#59]
I've reviewed the link sent by message receiver but the files for project 1 cannot be downloaded? Please advise....

**Comment by twostraws** [comment]
Download the files here: https://github.com/twostraws/HackingWithSwift/archive/main.zip

**Comment by JohnDavidGit** [comment]
I sincerely appreciate the prompt reply!
-John David
    On Friday, January 1, 2021, 01:27:58 PM PST, Paul Hudson <notifications@github.com> wrote:  
 
 


Download the files here: https://github.com/twostraws/HackingWithSwift/archive/main.zip
