### ISSUE TITLE
Project 26 Contribution

### ISSUE THREAD

**Issue by nxtlvl2t8k** [twostraws/HackingWithSwift#66]
I would like to share my Idea with you.  I have enjoyed your teachings and videos over the years.  I am a hobby programmer at best. I am going to work with your code to reverse the walls and vortex's and replace them with landing spots, multiple balls, and a shake motion to free/restart/reset the balls.  Here is an example of what I am talking about.  Maybe you can do it better and use it as an add-on to this project.  Thanks again for all your knowledge and sharing.  It has been a great learning site.
![IMG_1998](https://user-images.githubusercontent.com/16903935/140621501-5a9bd3d3-b0b5-46bf-874f-8e8119c94522.jpeg)
![IMG_1999](https://user-images.githubusercontent.com/16903935/140621507-6e02d6df-c7d6-4967-9544-f46f53a6bb9b.jpeg)

**Comment by twostraws** [comment]
Hello! I love to see folks take these projects and do exciting new things with them, and in particular release their versions of the projects on the App Store. However, I can't really accept those changes back onto the site – each tutorial is designed to teach a handful of things, and if I kept adding more to them it would grow increasingly large. Best of luck building your improvements!
