### ISSUE TITLE
Project 10: Cupcake image assets are missing

### ISSUE THREAD

**Issue by JakobTeske** [twostraws/HackingWithSwift#69]
In the book on page 267, a `project-10-files` folder is mentioned, with both `cupcakes@2x.jpg` and `cupcakes@3x.jpg` inside. 

In the current repo there is no `project-10-files folder`.

**Comment by veeramani-arthanari** [comment]
I didn't find it either in the repository. You can download from here

https://www.hackingwithswift.com/samples/img/cupcakes@2x.jpg
https://www.hackingwithswift.com/samples/img/cupcakes@3x.jpg

**Comment by twostraws** [comment]
The next book update will remove this image entirely; hopefully it will arrive soon!
