### ISSUE TITLE
Tutorial without Storyboard

### ISSUE THREAD

**Issue by sibeliusseraphini** [twostraws/HackingWithSwift#8]
Great tutorials!

You should add one tutorial without using Storyboard.
Only defining views using code or maybe using [Cartography](https://github.com/robb/Cartography) or other framework to simplify this

**Comment by twostraws** [comment]
This is not an issue; if you have general feedback please contact me via Twitter (@twostraws) or post on https://www.reddit.com/r/hackingwithswift
