### ISSUE TITLE
Project 2: Asset Files Flags

### ISSUE THREAD

**Issue by jan-sand** [twostraws/HackingWithSwift#80]
Very important! The flagfiles from Github are all writen in lowercase (If you add them by copy paste). But in the array on the SwiftUI-Tutorial every country starts with uppercase and then lowercase. So once you are coding and building, the asset files cant be found(---> case-sensitive). **You need to rename the files or easier rename the country names in the array.** Hope this helped.

**Comment by DavidGalindo23** [comment]
I have a dumb question how do I download the asset file of the flags ?

**Comment by CJH199X** [comment]
> I have a dumb question how do I download the asset file of the flags ?

I have the same question. Been trying for some time and can't figure it out.

**Comment by twostraws** [comment]
You can download the assets here: https://github.com/twostraws/HackingWithSwift/archive/refs/heads/main.zip

The files all have the correct case – just make sure you use the SwiftUI files, not the Classic files.
