### ISSUE TITLE
[Proposition] Project 2 - remove russian flag from assets

### ISSUE THREAD

**Issue by dmmaslenn** [twostraws/HackingWithSwift#81]
Hello, I know that this problem is not related to code. But its a bit disappointing to see terrorist country flag in context of this amazing course.
Great course, thank you for your job!

**Comment by twostraws** [comment]
I’m afraid this isn’t something I can easily address, because the course is in video form.

**Comment by 01GOD** [comment]
Remove the israeli flag. That would better address the main problem the World has.

**Comment by Skippy-the-meh** [comment]
@01god please keep your antisemitic bigotry to yourself or go express it away from polite society.

**Comment by cbscd** [comment]
Unsubscribed because of this

**Comment by Skippy-the-meh** [comment]
What….because of the Russian flag? That’s just silly. You can’t reasonably expect anyone to go back and change past references because of current events.
